[profile.release]
panic = 'unwind'

[workspace]
members = [
	"node/bench",
	"node/browser-testing",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc-client",
	"node/rpc",
    'runtime',
]
